# Copyright (C) 2016 Branden Archer <b.m.archer4@gmail.com>
# Copyright (C) 2016 Joshua D. Boyd <jdboyd@jdboyd.net>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

sudo: required
language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - USE_CMAKE=YES
  - USE_CMAKE=NO
  - USE_CMAKE=NO EXTRA_ARGS="--disable-fork --disable-subunit --enable-snprintf-replacement --enable-timer-replacement"
  - PRE_RELEASE_CHECK=YES
  global:
    - MY_PV=0.12.0

matrix:
  exclude:
  # There have been sporadic unit test failures with
  # timeout tests on OSX using CMake. Until these are
  # resolved, skipping these tests.
  - os: osx
    env: USE_CMAKE=YES
  - os: osx
    env: PRE_RELEASE_CHECK=YES

  include:
  # Only use scan-build once, the result should be the same
  # regardless of OS.
  - os: linux
    compiler: clang
    env: SCAN_BUILD=YES

before_script:
 - if [ "$(uname)" = "Linux" ]; then sudo apt-get update; sudo apt-get install -y texlive texinfo texi2html doxygen; fi
 - if [ "$(uname)" = "Darwin" ]; then brew update; brew cask install mactex; brew install texi2html texinfo doxygen; fi

jobs:
  include:
    - stage: Test builds
    - stage: Deploy
      if: tag =~ ^v.* AND branch = master AND os = linux
      deploy:
        provider: releases
        api_key:
          secure: <REPLACE_ME_WITH_SECURE_KEY>
        file:
          - dist/check-${MY_PV}.x86_64.deb
          - dist/check-${MY_PV}.x86_64.rpm
        on:
          repo: libcheck/check
          branch: master
          tags: true
        skip_cleanup: true
      script:
        - cmake -D CMAKE_BUILD_TYPE=Release ./
        - make package

script:
  - chmod +x travis.sh
  - ./travis.sh
